version: "3"

services:
  traefik:
    command:
      - --accessLog=${TRAEFIK_ACCESSLOG}
      - --api.dashboard=${TRAEFIK_API_DASHBOARD}
      - --api.debug=${TRAEFIK_API_DEBUG}
      - --api.insecure=${TRAEFIK_API_INSECURE}
      - --certificatesresolvers.dns.acme.dnschallenge.delayBeforeCheck=30
      - --certificatesResolvers.dns.acme.dnsChallenge.provider=${TRAEFIK_ACME_DNSCHALLENGE_PROVIDER}
      - --certificatesresolvers.dns.acme.dnschallenge.resolvers=${TRAEFIK_ACME_DNSCHALLENGE_RESOLVERS}
      - --certificatesResolvers.dns.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesResolvers.dns.acme.storage=/acme/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --log.level=${TRAEFIK_LOG_LEVEL}
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=core.traefik.net
    image: traefik:v2.10
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_BASICAUTH}
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.middlewares: traefik-auth
      traefik.http.routers.traefik.rule: Host(`traefik.${FQDN}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: dns
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    networks:
      core.traefik.net: {}
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    restart: unless-stopped
    volumes:
      - core.traefik.acme:/acme
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  core.traefik.acme:
    name: core.traefik.acme

networks:
  core.traefik.net:
    name: core.traefik.net
